package com.VideoInfo.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIDEO_INFO".
 */
public class VideoInfo {

    private Long id;
    private String file_Name;
    private String file_Size;
    private String file_Path;
    private String file_Duration;
    private String file_Extention;

    public VideoInfo() {
    }

    public VideoInfo(Long id) {
        this.id = id;
    }

    public VideoInfo(Long id, String file_Name, String file_Size, String file_Path, String file_Duration, String file_Extention) {
        this.id = id;
        this.file_Name = file_Name;
        this.file_Size = file_Size;
        this.file_Path = file_Path;
        this.file_Duration = file_Duration;
        this.file_Extention = file_Extention;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFile_Name() {
        return file_Name;
    }

    public void setFile_Name(String file_Name) {
        this.file_Name = file_Name;
    }

    public String getFile_Size() {
        return file_Size;
    }

    public void setFile_Size(String file_Size) {
        this.file_Size = file_Size;
    }

    public String getFile_Path() {
        return file_Path;
    }

    public void setFile_Path(String file_Path) {
        this.file_Path = file_Path;
    }

    public String getFile_Duration() {
        return file_Duration;
    }

    public void setFile_Duration(String file_Duration) {
        this.file_Duration = file_Duration;
    }

    public String getFile_Extention() {
        return file_Extention;
    }

    public void setFile_Extention(String file_Extention) {
        this.file_Extention = file_Extention;
    }

}
