package com.VideoInfo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.VideoInfo.entity.VideoInfo;
import com.VideoInfo.entity.FileFolder;

import com.VideoInfo.dao.VideoInfoDao;
import com.VideoInfo.dao.FileFolderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoInfoDaoConfig;
    private final DaoConfig fileFolderDaoConfig;

    private final VideoInfoDao videoInfoDao;
    private final FileFolderDao fileFolderDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoInfoDaoConfig = daoConfigMap.get(VideoInfoDao.class).clone();
        videoInfoDaoConfig.initIdentityScope(type);

        fileFolderDaoConfig = daoConfigMap.get(FileFolderDao.class).clone();
        fileFolderDaoConfig.initIdentityScope(type);

        videoInfoDao = new VideoInfoDao(videoInfoDaoConfig, this);
        fileFolderDao = new FileFolderDao(fileFolderDaoConfig, this);

        registerDao(VideoInfo.class, videoInfoDao);
        registerDao(FileFolder.class, fileFolderDao);
    }
    
    public void clear() {
        videoInfoDaoConfig.getIdentityScope().clear();
        fileFolderDaoConfig.getIdentityScope().clear();
    }

    public VideoInfoDao getVideoInfoDao() {
        return videoInfoDao;
    }

    public FileFolderDao getFileFolderDao() {
        return fileFolderDao;
    }

}
