package com.VideoInfo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.VideoInfo.entity.FileFolder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_FOLDER".
*/
public class FileFolderDao extends AbstractDao<FileFolder, Long> {

    public static final String TABLENAME = "FILE_FOLDER";

    /**
     * Properties of entity FileFolder.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property File_Name = new Property(1, String.class, "file_Name", false, "FILE__NAME");
        public final static Property File_Path = new Property(2, String.class, "file_Path", false, "FILE__PATH");
        public final static Property File_check = new Property(3, Boolean.class, "file_check", false, "FILE_CHECK");
    };


    public FileFolderDao(DaoConfig config) {
        super(config);
    }
    
    public FileFolderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_FOLDER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FILE__NAME\" TEXT," + // 1: file_Name
                "\"FILE__PATH\" TEXT," + // 2: file_Path
                "\"FILE_CHECK\" INTEGER);"); // 3: file_check
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_FOLDER\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, FileFolder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String file_Name = entity.getFile_Name();
        if (file_Name != null) {
            stmt.bindString(2, file_Name);
        }
 
        String file_Path = entity.getFile_Path();
        if (file_Path != null) {
            stmt.bindString(3, file_Path);
        }
 
        Boolean file_check = entity.getFile_check();
        if (file_check != null) {
            stmt.bindLong(4, file_check ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public FileFolder readEntity(Cursor cursor, int offset) {
        FileFolder entity = new FileFolder( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // file_Name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // file_Path
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // file_check
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, FileFolder entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFile_Name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFile_Path(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFile_check(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(FileFolder entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(FileFolder entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
